config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  
  root "static_pages#homepage"
  
  resources :contestants do
    get 'add_points', on: :member
  end

  resources :episode_points, only: [:index, :destroy]

  resources :leagues, only: [:index, :show]

  resources :teams

  resources :users

  resources :charts do
    get :points_per_episode, on: :collection
  end
end

app/models/contestant.rb
# == Schema Information
#
# Table name: contestants
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  age                :integer
#  occupation         :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  eliminated_episode :integer
#

class Contestant < ActiveRecord::Base

  has_many :contestant_teams, :dependent => :destroy
  has_many :teams, through: :contestant_teams

  has_many :episode_points
  accepts_nested_attributes_for :episode_points, :reject_if => lambda { |ep| ep[:scoring_rule_id].blank? }

  scope :still_in, -> { where(eliminated_episode: nil) }

end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  before_action :set_contestant, only: [:show, :edit, :update, :add_points]
  before_action :authenticate_user!, only: [:add_points, :update]

  # GET /contestants
  # GET /contestants.json
  def index
    @contestants = Contestant.all.order(:name)
  end

  # PATCH/PUT /contestants/1
  # PATCH/PUT /contestants/1.json
  def update
    respond_to do |format|
      if @contestant.update(contestant_params)
        format.html { redirect_to contestants_path, notice: '#{@contestant.name} was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def add_points
    @episode_number = @contestant.episode_points.maximum(:episode_number).to_i + 1
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contestant
      @contestant = Contestant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contestant_params
      params.require(:contestant).permit(:name, :age, :occupation, :eliminated_episode, episode_points_attributes: [:id, :episode_number, :scoring_rule_id])
    end
end

app/helpers/contestants_helper.rb
module ContestantsHelper

  def current_status_class c
    c.eliminated_episode.present? ? 'strikethrough bg-danger' : nil
  end

  def current_status_text_class c
    c.eliminated_episode.present? ? 'strikethrough' : nil
  end
end

app/views/contestants/add_points.slim
h1 Add Points for #{@contestant.name}

hr
= form_for @contestant do |f|
  .form-group.row.form-inline
    .col-xs-2 = f.label :eliminated_episode, class: "control-label"
    .col-xs-3 = f.number_field :eliminated_episode, class: "form-control col-xs-3"
  hr
  = f.fields_for :episode_points, [EpisodePoint.new]*7 do |episode_point|
    .form-group.row.form-inline
      .col-xs-2 = episode_point.number_field :episode_number, value: @episode_number, class: "form-control col-xs-2"
      .col-xs-8 = episode_point.collection_select :scoring_rule_id, ScoringRule.all.order(:description, :points) , :id, :formated_points_and_description, {include_blank: true}, {class: "form-control col-xs-8"}
  .form-group
    = f.submit class: "btn btn-primary"

app/views/contestants/index.slim
h1.text-center The Lucky Contestants
.row
  .col-md-10.col-md-offset-1
    table.table
      thead
        tr
          th Name
          th Age
          th Occupation

      tbody
        - @contestants.each do |contestant|
          tr[class="#{current_status_class(contestant)}"]
            td.col-md-2 = link_to contestant.name, "http://abc.go.com/shows/the-bachelorette/cast/#{contestant.name.parameterize}", target: "_blank"
            td.col-md-1 = contestant.age
            td.col-md-3  = contestant.occupation
            td.col-md-1 = link_to 'See Points', episode_points_path(anchor: "contestant_#{contestant.id}")
            - if current_user.present?
              td.col-md-1 = link_to 'Add Points', add_points_contestant_path(contestant)