config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  
  root "static_pages#homepage"
  
  resources :contestants do
    get 'add_points', on: :member
  end

  resources :episode_points, only: [:index, :destroy]

  resources :leagues, only: [:index, :show]

  resources :teams

  resources :users

  resources :charts do
    get :points_per_episode, on: :collection
  end
end

app/models/league.rb
# == Schema Information
#
# Table name: leagues
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  season_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class League < ActiveRecord::Base

  has_many :league_users, :dependent => :destroy
  has_many :users, through: :league_users
  has_many :teams

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_contestant, only: [:show]

  def index
    @leagues = League.all
  end

  def show
    @teams = @league.teams.sort_by(&:current_score).reverse!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contestant
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name, :season_id)
    end
end

app/views/leagues/index.slim
.row
  .col-md-8.col-md-offset-2.col-xs-12.text-center
    p Find your league, find true love.
    - @leagues.each do |league|
      .row
        .col-md-10.col-md-offset-1.col-xs-12
          hr
          .pull-left 
            h3 = league.name
            p #{league.users.count} players
          .pull-right= link_to "View", league_path(league), class: "btn btn-danger btn-lg margin-top-md"

app/views/leagues/show.slim
h1.text-center = @league.name
.row
  .col-md-10.col-md-offset-1
    = line_chart points_per_episode_charts_path(league_id: @league.id), discrete: true, xtitle: "Episode", ytitle: "Points"
    table.table.table-striped
      thead
        tr
          th User
          th Contestants
          th Current Score
          th Remaining Contestants
          th

      tbody
        - @teams.each do |team|
          tr
            td= team.user.name
            td
              ul
                - team.contestants.each do |contestant|
                  li[class="#{current_status_text_class(contestant)}"] = link_to contestant.name, episode_points_path(anchor: "contestant_#{contestant.id}")
            td = team.current_score
            td = team.contestants.still_in.count
            td = link_to "Detailed Scoring", team_path(team)
    br