config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  
  root "static_pages#homepage"
  
  resources :contestants do
    get 'add_points', on: :member
  end

  resources :episode_points, only: [:index, :destroy]

  resources :leagues, only: [:index, :show]

  resources :teams

  resources :users

  resources :charts do
    get :points_per_episode, on: :collection
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheRightReasons</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'The Right Reasons', root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Hi #{current_user.name}", "#" %></li>
          <% end %>
          <li><%= link_to 'Leagues', leagues_path %></li>
          <li><%= link_to 'Contestants', contestants_path %></li>
          <li><%= link_to 'Episode Points', episode_points_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

<div class="container-fluid" role="main">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</div>

</body>
</html>